<?php
$helper = Mage::helper('mdg_giftregistry');
$loadRegistry = Mage::getSingleton('core/session')->getLoadedRegistry();
?>
<?php if ($loadRegistry): ?>
    <form action="<?php echo $this->getUrl('giftregistry/index/editPost/') ?>" method="post" id="form-validate">
        <fieldset>
            <?php echo $this->getBlockHtml('formkey') ?>
            <input type="hidden" name="type_id" value="<?php echo $loadRegistry->getTypeId(); ?>">
            <ul class="form-list">
                <li class="field">
                    <input type="text" name="event_name", id="event_name" value="<?php echo $loadRegistry->getEventName(); ?>" title="<?php echo $this->__('Event Name') ?>">
                    <label class="giftreg" for="event_name"><?php echo $this->__('Event Name') ?></label>
                </li>
                <li class="field">
                    <input type="text" name="event_location", id="event_location" value="<?php echo $loadRegistry->getEventLocation(); ?>" title="<?php echo $this->__('Event Location') ?>">
                    <label class="giftreg" for="event_name"><?php echo $this->__('Event Location') ?></label>
                </li>
                <li class="field">
                    <input type="text" name="event_country", id="event_country" value="<?php echo $loadRegistry->getEventCountry(); ?>" title="<?php echo $this->__('Event Country') ?>">
                    <label class="giftreg" for="event_name"><?php echo $this->__('Event Country') ?></label>
                </li>
            </ul>
            <div class="button-set">
                <button class="button" type="submit" title="<?php echo $this->__('Save'); ?>">
                    <span><?php echo $this->__('Save'); ?></span>
                </button>
            </div>
        </fieldset>
    </form>
    <script type="text/javascript">
        //<! [CDATA[
        var dataForm = new VarienForm('form-validate', true);
        //]]>
    </script>
<?php else: ?>
    <h2><?php echo $this->__('There was a problem loading the registry'); ?></h2>
<?php endif; ?>
