<?php
$helper = Mage::helper('mdg_giftregistry');
$_collection = $this->getCustomerRegistries();
?>
<div class="customer-list">
    <?php if (!$_collection->count()): ?>
        <h2><?php echo $this->__('You have no registries.') ?></h2>
        <a href="<?php echo $this->getUrl('giftregistry/index/new/'); ?>"><?php echo $this->__('Click here to create a new Gift Registry'); ?></a>
    <?php else: ?>
        <ul>
            <?php foreach ($_collection as $registry): ?>
                <li>
                    <h3><?php echo $registry->getEventName(); ?></h3>
                    <p>
                        <strong>
                            <?php echo $this->__('Event Location:'); ?>
                            <?php echo $registry->getEventLocation(); ?>
                        </strong>
                    </p>
                    <a href="<?php echo $this->getUrl('giftregistry/view/view', array('query' => array('registry_id' => $registry->getEntityId()))) ?>">
                        <?php echo $this->__('View Registry'); ?>
                    </a>
                    <?php if($helper->isOwnerRegistry()): ?>
                    <a href="<?php echo $this->getUrl('giftregistry/index/edit', array('query' => array('registry_id' => $registry->getEntityId()))) ?>">
                        <?php echo $this->__('Edit Registry'); ?>
                    </a>
                    <a href="<?php echo $this->getUrl('giftregistry/index/delete', array('query' => array('registry_id' => $registry->getEntityId()))) ?>">
                        <?php echo $this->__('Delete Registry'); ?>
                    </a>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
</div>
